/****************************************************************************
 Copyright (c) 2008-2010 Ricardo Quesada
 Copyright (c) 2011-2012 cocos2d-x.org
 Copyright (c) 2013-2014 Chukong Technologies Inc.

 http://www.cocos2d-x.org

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 ****************************************************************************/

var CCB_VERSION = 6;
var CCB_LEGACY_VERSION = 5;

var CCB_PROPTYPE_POSITION = 0;
var CCB_PROPTYPE_SIZE = 1;
var CCB_PROPTYPE_POINT = 2;
var CCB_PROPTYPE_POINTLOCK = 3;
var CCB_PROPTYPE_SCALELOCK = 4;
var CCB_PROPTYPE_DEGREES = 5;
var CCB_PROPTYPE_INTEGER = 6;
var CCB_PROPTYPE_FLOAT = 7;
var CCB_PROPTYPE_FLOATVAR = 8;
var CCB_PROPTYPE_CHECK = 9;
var CCB_PROPTYPE_SPRITEFRAME = 10;
var CCB_PROPTYPE_TEXTURE = 11;
var CCB_PROPTYPE_BYTE = 12;
var CCB_PROPTYPE_COLOR3 = 13;
var CCB_PROPTYPE_COLOR4VAR = 14;
var CCB_PROPTYPE_FLIP = 15;
var CCB_PROPTYPE_BLENDMODE = 16;
var CCB_PROPTYPE_FNTFILE = 17;
var CCB_PROPTYPE_TEXT = 18;
var CCB_PROPTYPE_FONTTTF = 19;
var CCB_PROPTYPE_INTEGERLABELED = 20;
var CCB_PROPTYPE_BLOCK = 21;
var CCB_PROPTYPE_ANIMATION = 22;
var CCB_PROPTYPE_CCBFILE = 23;
var CCB_PROPTYPE_STRING = 24;
var CCB_PROPTYPE_BLOCKCCCONTROL = 25;
var CCB_PROPTYPE_FLOATSCALE = 26;
var CCB_PROPTYPE_FLOATXY = 27;
var CCB_PROPTYPE_COLOR4 = 28;
var CCB_PROPTYPE_NODEREFERENCE = 29;
var CCB_PROPTYPE_FLOATCHECK = 30;
var CCB_PROPTYPE_EFFECTCONTROL = 31;
var CCB_PROPTYPE_SOUNDFILE = 32;
var CCB_PROPTYPE_OFFSETS = 33;
var CCB_PROPTYPE_MEMBERVARASSIGNMENT = 34;

var CCB_FLOAT0 = 0;
var CCB_FLOAT1 = 1;
var CCB_FLOAT_MINUS1 = 2;
var CCB_FLOAT05 = 3;
var CCB_FLOAT_INTEGER = 4;
var CCB_FLOAT_FULL = 5;

var CCB_PLATFORM_ALL = 0;
var CCB_PLATFORM_IOS = 1;
var CCB_PLATFORM_MAC = 2;

var CCB_TARGETTYPE_NONE = 0;
var CCB_TARGETTYPE_DOCUMENTROOT = 1;
var CCB_TARGETTYPE_OWNER = 2;

var CCB_KEYFRAME_EASING_INSTANT = 0;
var CCB_KEYFRAME_EASING_LINEAR = 1;
var CCB_KEYFRAME_EASING_CUBIC_IN = 2;
var CCB_KEYFRAME_EASING_CUBIC_OUT = 3;
var CCB_KEYFRAME_EASING_CUBIC_INOUT = 4;
var CCB_KEYFRAME_EASING_ELASTIC_IN = 5;
var CCB_KEYFRAME_EASING_ELASTIC_OUT = 6;
var CCB_KEYFRAME_EASING_ELASTIC_INOUT = 7;
var CCB_KEYFRAME_EASING_BOUNCE_IN = 8;
var CCB_KEYFRAME_EASING_BOUNCE_OUT = 9;
var CCB_KEYFRAME_EASING_BOUNCE_INOUT = 10;
var CCB_KEYFRAME_EASING_BACK_IN = 11;
var CCB_KEYFRAME_EASING_BACK_OUT = 12;
var CCB_KEYFRAME_EASING_BACK_INOUT = 13;

var CCB_POSITIONTYPE_RELATIVE_BOTTOM_LEFT = 0;
var CCB_POSITIONTYPE_RELATIVE_TOP_LEFT = 1;
var CCB_POSITIONTYPE_RELATIVE_TOP_RIGHT = 2;
var CCB_POSITIONTYPE_RELATIVE_BOTTOM_RIGHT = 3;
var CCB_POSITIONTYPE_PERCENT = 4;
var CCB_POSITIONTYPE_MULTIPLY_RESOLUTION = 5;

var CCB_SIZETYPE_ABSOLUTE = 0;
var CCB_SIZETYPE_PERCENT = 1;
var CCB_SIZETYPE_RELATIVE_CONTAINER = 2;
var CCB_SIZETYPE_HORIZONTAL_PERCENT = 3;
var CCB_SIZETYPE_VERTICAL_PERCENT = 4;
var CCB_SIZETYPE_MULTIPLY_RESOLUTION = 5;

var CCB_SCALETYPE_ABSOLUTE = 0;
var CCB_SCALETYPE_MULTIPLY_RESOLUTION = 1;

cc.BuilderFile = cc.Node.extend({
    _ccbFileNode:null,

    getCCBFileNode:function () {
        return this._ccbFileNode;
    },
    setCCBFileNode:function (node) {
        this._ccbFileNode = node;
    }
});

cc.BuilderFile.create = function () {
    return new cc.BuilderFile();
};

/**
 * Parse CCBI file which is generated by CocosBuilder
 */
cc.BuilderReader = cc.Class.extend({
    _jsControlled:false,
    _data:null,
    _ccbRootPath:"",

    _bytes:0,
    _currentByte:0,
    _currentBit:0,

    _stringCache:null,
    _loadedSpriteSheets:null,

    _owner:null,
    _animationManager:null,
    _animationManagers:null,
    _animatedProps:null,

    _ccNodeLoaderLibrary:null,
    _ccNodeLoaderListener:null,
    _ccbMemberVariableAssigner:null,
    _ccbSelectorResolver:null,

    _ownerOutletNames:null,
    _ownerOutletNodes:null,
    _nodesWithAnimationManagers:null,
    _animationManagerForNodes:null,
    _fileVersion:0,

    _ownerCallbackNames:null,
    _ownerCallbackNodes:null,
    _ownerCallbackEvents:null,

    _readNodeGraphFromData:false,

    ctor:function (ccNodeLoaderLibrary, ccbMemberVariableAssigner, ccbSelectorResolver, ccNodeLoaderListener) {
        this._stringCache = [];
        this._loadedSpriteSheets = [];
        this._currentBit = -1;
        this._currentByte = -1;

        if (arguments.length !== 0) {
            if (ccNodeLoaderLibrary instanceof cc.BuilderReader) {
                var ccbReader = ccNodeLoaderLibrary;

                /* Borrow data from the 'parent' CCBReader. */
                this._loadedSpriteSheets = ccbReader._loadedSpriteSheets;
                this._ccNodeLoaderLibrary = ccbReader._ccNodeLoaderLibrary;

                this._ccbMemberVariableAssigner = ccbReader._ccbMemberVariableAssigner;
                this._ccbSelectorResolver = ccbReader._ccbSelectorResolver;
                this._ccNodeLoaderListener = ccbReader._ccNodeLoaderListener;

                this._ownerCallbackNames = ccbReader._ownerCallbackNames;
                this._ownerCallbackNodes = ccbReader._ownerCallbackNodes;
                this._ownerCallbackEvents = ccbReader._ownerCallbackEvents;
                this._ownerOutletNames = ccbReader._ownerOutletNames;
                this._ownerOutletNodes = ccbReader._ownerOutletNodes;
                this._ccbRootPath = ccbReader._ccbRootPath;
                this._currentCCBFileName = ccbReader._currentCCBFileName;
            } else {
                this._ccNodeLoaderLibrary = ccNodeLoaderLibrary;
                this._ccbMemberVariableAssigner = ccbMemberVariableAssigner;
                this._ccbSelectorResolver = ccbSelectorResolver;
                this._ccNodeLoaderListener = ccNodeLoaderListener;
            }
        }
    },

    getCCBRootPath:function () {
        return this._ccbRootPath;
    },

    setCCBRootPath:function (rootPath) {
        this._ccbRootPath = rootPath;
    },

    initWithData:function (data, owner) {
        //setup action manager
        this._animationManager = new cc.BuilderAnimationManager();

        //setup byte array
        //Array replace to CCData in Javascript
        this._data = data;
        this._bytes = data.length;
        this._currentBit = 0;
        this._currentByte = 0;

        this._owner = owner;

        //setup resolution scale and container size
        this._animationManager.setRootContainerSize(cc.director.getWinSize());

        return true;
    },

    _loadBinarySync : function(url){
        var self = this;
        var req = this.getXMLHttpRequest();
        var errInfo = "load " + url + " failed!";
        req.open('GET', url, false);
        var arrayInfo = null;
        if (/msie/i.test(navigator.userAgent) && !/opera/i.test(navigator.userAgent)) {
            req.setRequestHeader("Accept-Charset", "x-user-defined");
            req.send(null);
            if (req.status !== 200) {
                cc.log(errInfo);
                return null;
            }

            var fileContents = cc._convertResponseBodyToText(req["responseBody"]);
            if (fileContents) {
                arrayInfo = this._stringConvertToArray(fileContents);
                this._fileDataCache[url] = arrayInfo;
            }
        } else {
            if (req.overrideMimeType)
                req.overrideMimeType('text\/plain; charset=x-user-defined');
            req.send(null);
            if (req.status !== 200) {
                cc.log(errInfo);
                return null;
            }

            arrayInfo = this._stringConvertToArray(req.responseText);
            this._fileDataCache[url] = arrayInfo;
        }
        return arrayInfo;
    },

    readNodeGraphFromFile:function (ccbFileName, owner, parentSize, animationManager) {
        this._currentCCBFileName = ccbFileName;
        if (parentSize == null) {
            parentSize = cc.director.getWinSize();
        } else if (parentSize instanceof  cc.BuilderAnimationManager) {
            animationManager = parentSize;
            parentSize = cc.director.getWinSize();
        }

        var data = cc.loader.getRes(ccbFileName);
        if(!data){
            var realUrl = cc.loader.getUrl(ccbFileName);
            data = cc.loader.loadBinarySync(realUrl);
            cc.loader.cache[ccbFileName] = data;
        }

        return this.readNodeGraphFromData(data, owner, parentSize, animationManager);
    },

    readNodeGraphFromData:function (data, owner, parentSize) {
        this.initWithData(data, owner);
        var locAnimationManager = this._animationManager;
        locAnimationManager.setRootContainerSize(parentSize);
        locAnimationManager.setOwner(owner);

        this._ownerOutletNames = [];
        this._ownerOutletNodes = [];
        this._ownerCallbackNames = [];
        this._ownerCallbackNodes = [];
        this._ownerCallbackEvents = [];
        this._animationManagers = new cc._Dictionary();

        var nodeGraph = this.readFileWithCleanUp(true);

        if (nodeGraph && locAnimationManager.getAutoPlaySequenceId() !== -1) {
            //auto play animations
            locAnimationManager.runAnimations(locAnimationManager.getAutoPlaySequenceId(), 0);
        }

        if (this._jsControlled) {
            var locNodes = [];
            var locAnimations = [];

            var locAnimationManagers = this._animationManagers;
            var getAllKeys = locAnimationManagers.allKeys();
            for (var i = 0; i < getAllKeys.length; i++) {
                locNodes.push(getAllKeys[i]);
                locAnimations.push(locAnimationManagers.objectForKey(getAllKeys[i]));
            }

            this._nodesWithAnimationManagers = locNodes;
            this._animationManagerForNodes = locAnimations;
        }

        return nodeGraph;
    },

    createSceneWithNodeGraphFromFile:function (ccbFileName, owner, parentSize, animationManager) {
        var node = this.readNodeGraphFromFile(ccbFileName, owner, parentSize, animationManager);
        var scene = new cc.Scene();
        scene.addChild(node);
        return scene;
    },

    getCCBMemberVariableAssigner:function () {
        return this._ccbMemberVariableAssigner;
    },

    getCCBSelectorResolver:function () {
        return this._ccbSelectorResolver;
    },

    getAnimationManager:function () {
        return this._animationManager;
    },

    setAnimationManager:function (animationManager) {
        this._animationManager = animationManager;
    },

    getAnimatedProperties:function () {
        return this._animatedProps;
    },

    getLoadedSpriteSheet:function () {
        return this._loadedSpriteSheets;
    },

    getOwner:function () {
        return this._owner;
    },

    getFileVersion:function () {
        return this._fileVersion || 0;
    },

    _pushUniquePathCandidate:function (list, value) {
        if (value != null && value !== "" && list.indexOf(value) === -1) {
            list.push(value);
        }
    },

    _getRootPathCandidatesV6:function () {
        var candidates = [];
        this._pushUniquePathCandidate(candidates, this._ccbRootPath || "");
        this._pushUniquePathCandidate(candidates, cc.BuilderReader.getResourcePath ? cc.BuilderReader.getResourcePath() : "");
        this._pushUniquePathCandidate(candidates, "res/");
        this._pushUniquePathCandidate(candidates, "");
        return candidates;
    },

    _resourceExistsV6:function (resourcePath) {
        if (!resourcePath || !cc.loader || !cc.loader.getRes) {
            return false;
        }
        return !!cc.loader.getRes(resourcePath);
    },

    _getSpriteFrameExactV6:function (frameName) {
        if (!frameName || !cc.spriteFrameCache) {
            return null;
        }
        var frameCache = cc.spriteFrameCache;
        var spriteFrames = frameCache._spriteFrames || {};
        var frame = spriteFrames[frameName];
        if (!frame) {
            var aliases = frameCache._spriteFramesAliases || {};
            var alias = aliases[frameName];
            if (alias) {
                frame = spriteFrames[alias.toString()];
                if (!frame) {
                    delete aliases[frameName];
                }
            }
        }
        return frame || null;
    },

    _findSpriteFrameInCacheV6:function (spriteFile, allowBaseName) {
        if (!spriteFile) {
            return null;
        }

        var frame = this._getSpriteFrameExactV6(spriteFile);
        if (frame) {
            return frame;
        }

        if (allowBaseName) {
            var baseName = cc.BuilderReader.lastPathComponent(spriteFile);
            frame = this._getSpriteFrameExactV6(baseName);
            if (frame) {
                return frame;
            }
        }

        return null;
    },

    _createSpriteFrameFromPlistV6:function (plistPath, frameName, aliasName) {
        if (!plistPath || !frameName || !cc.loader || !cc.spriteFrameCache) {
            return null;
        }
        var plistData = cc.loader.getRes(plistPath);
        if (!plistData || !plistData.frames) {
            return null;
        }

        var frameCache = cc.spriteFrameCache;
        var frameConfig = frameCache._frameConfigCache[plistPath];
        if (!frameConfig) {
            if (typeof frameCache._getFrameConfigByJsonObject === "function") {
                frameConfig = frameCache._getFrameConfigByJsonObject(plistPath, plistData);
            } else if (typeof frameCache._parseFrameConfig === "function") {
                frameConfig = frameCache._parseFrameConfig(plistData);
                frameCache._frameConfigCache[plistPath] = frameConfig;
            }
        }
        if (!frameConfig || !frameConfig.frames || !frameConfig.frames[frameName]) {
            return null;
        }

        var frame = frameConfig.frames[frameName];
        var texturePath = cc.path.changeBasename(plistPath, frameConfig.meta.image || ".png");
        var texture = cc.textureCache.addImage(texturePath);
        if (!texture) {
            return null;
        }

        var spriteFrame = new cc.SpriteFrame(texture, frame.rect, frame.rotated, frame.offset, frame.size);
        if (aliasName) {
            frameCache._spriteFrames[aliasName] = spriteFrame;
        }
        return spriteFrame;
    },

    _findSpriteFrameInPlistV6:function (spriteFile) {
        if (!spriteFile || spriteFile.indexOf("/") === -1) {
            return null;
        }

        var slashPos = spriteFile.lastIndexOf("/");
        var sheetPrefix = spriteFile.substring(0, slashPos);
        var basePrefix = cc.BuilderReader.lastPathComponent(sheetPrefix);
        var baseName = cc.BuilderReader.lastPathComponent(spriteFile);
        var roots = this._getRootPathCandidatesV6();
        var plistCandidates = [];

        for (var i = 0; i < roots.length; i++) {
            this._pushUniquePathCandidate(plistCandidates, roots[i] + sheetPrefix + ".plist");
            if (basePrefix !== sheetPrefix) {
                this._pushUniquePathCandidate(plistCandidates, roots[i] + basePrefix + ".plist");
            }
        }

        for (i = 0; i < plistCandidates.length; i++) {
            var plistPath = plistCandidates[i];
            var frame = this._createSpriteFrameFromPlistV6(plistPath, spriteFile, spriteFile);
            if (frame) {
                return frame;
            }
            frame = this._createSpriteFrameFromPlistV6(plistPath, baseName, spriteFile);
            if (frame) {
                return frame;
            }
        }

        return null;
    },

    _loadSpriteSheetForSpriteFrameV6:function (spriteFile) {
        if (!spriteFile || spriteFile.indexOf("/") === -1) {
            return false;
        }

        var slashPos = spriteFile.lastIndexOf("/");
        var sheetPrefix = spriteFile.substring(0, slashPos);
        var basePrefix = cc.BuilderReader.lastPathComponent(sheetPrefix);
        var roots = this._getRootPathCandidatesV6();
        var plistCandidates = [];
        var i;

        for (i = 0; i < roots.length; i++) {
            this._pushUniquePathCandidate(plistCandidates, roots[i] + sheetPrefix + ".plist");
            if (basePrefix !== sheetPrefix) {
                this._pushUniquePathCandidate(plistCandidates, roots[i] + basePrefix + ".plist");
            }
        }

        var loadedSpriteSheets = this._loadedSpriteSheets;
        for (i = 0; i < plistCandidates.length; i++) {
            var plistPath = plistCandidates[i];
            if (!this._resourceExistsV6(plistPath)) {
                continue;
            }
            if (loadedSpriteSheets.indexOf(plistPath) === -1) {
                cc.spriteFrameCache.addSpriteFrames(plistPath);
                loadedSpriteSheets.push(plistPath);
            }
            if (this._findSpriteFrameInCacheV6(spriteFile, true)) {
                return true;
            }
        }

        return false;
    },

    _loadTextureSpriteFrameV6:function (spriteFile) {
        if (!spriteFile) {
            return null;
        }

        var roots = this._getRootPathCandidatesV6();
        var candidates = [];
        var baseName = cc.BuilderReader.lastPathComponent(spriteFile);
        var i;

        for (i = 0; i < roots.length; i++) {
            this._pushUniquePathCandidate(candidates, roots[i] + baseName);
            this._pushUniquePathCandidate(candidates, roots[i] + spriteFile);
        }

        for (i = 0; i < candidates.length; i++) {
            var imagePath = candidates[i];
            if (!this._resourceExistsV6(imagePath)) {
                continue;
            }
            var texture = cc.textureCache.addImage(imagePath);
            if (!texture) {
                continue;
            }
            var locContentSize = texture.getContentSize();
            var bounds = cc.rect(0, 0, locContentSize.width, locContentSize.height);
            return new cc.SpriteFrame(texture, bounds);
        }

        return null;
    },

    _resolveSpriteFrameV6:function (spriteFile) {
        var frame = this._findSpriteFrameInCacheV6(spriteFile, false);
        if (frame) {
            return frame;
        }

        frame = this._findSpriteFrameInPlistV6(spriteFile);
        if (frame) {
            return frame;
        }

        this._loadSpriteSheetForSpriteFrameV6(spriteFile);
        frame = this._findSpriteFrameInCacheV6(spriteFile, true);
        if (frame) {
            return frame;
        }

        return this._loadTextureSpriteFrameV6(spriteFile);
    },

    readInt:function (signed) {
        var numBits = 0;
        while (!this._getBit()) {
            numBits++;
        }

        var current = 0;
        for (var a = numBits - 1; a >= 0; a--) {
            if (this._getBit()) {
                current |= 1 << a;
            }
        }
        current |= 1 << numBits;

        var num;
        if (signed) {
            var s = current % 2;
            if (s) {
                num = 0 | (current / 2);
            } else {
                num = 0 | (-current / 2);
            }
        } else {
            num = current - 1;
        }

        this._alignBits();

        return num;
    },

    readByte:function () {
        var byteValue = this._data[this._currentByte];
        this._currentByte++;
        return byteValue;
    },

    readBool:function () {
        return (0 !== this.readByte());
    },

    readFloat:function () {
        var type = this.readByte();

        switch (type) {
            case CCB_FLOAT0:
                return 0;
            case CCB_FLOAT1:
                return 1;
            case CCB_FLOAT_MINUS1:
                return -1;
            case CCB_FLOAT05:
                return 0.5;
            case CCB_FLOAT_INTEGER:
                return this.readInt(true);
            default:
                /* using a memcpy since the compiler isn't
                 * doing the float ptr math correctly on device.
                 */
                var pF = this._decodeFloat(23, 8); //this._bytes + this._currentByte;
                //this._currentByte += 4;
                return pF;
        }
    },

    _decodeFloat:function (precisionBits, exponentBits) {
        var length = precisionBits + exponentBits + 1;
        var size = length >> 3;
        this._checkSize(length);

        var bias = Math.pow(2, exponentBits - 1) - 1;
        var signal = this._readBitsOnly(precisionBits + exponentBits, 1, size);
        var exponent = this._readBitsOnly(precisionBits, exponentBits, size);
        var significand = 0;
        var divisor = 2;
        var curByte = 0; //length + (-precisionBits >> 3) - 1;
        do {
            var byteValue = this._readByteOnly(++curByte, size);
            var startBit = precisionBits % 8 || 8;
            var mask = 1 << startBit;
            while (mask >>= 1) {
                if (byteValue & mask) {
                    significand += 1 / divisor;
                }
                divisor *= 2;
            }
        } while (precisionBits -= startBit);

        this._currentByte += size;

        return exponent === (bias << 1) + 1 ? significand ? NaN : signal ? -Infinity : +Infinity
            : (1 + signal * -2) * (exponent || significand ? !exponent ? Math.pow(2, -bias + 1) * significand
            : Math.pow(2, exponent - bias) * (1 + significand) : 0);
    },

    _readBitsOnly:function (start, length, size) {
        var offsetLeft = (start + length) % 8;
        var offsetRight = start % 8;
        var curByte = size - (start >> 3) - 1;
        var lastByte = size + (-(start + length) >> 3);
        var diff = curByte - lastByte;

        var sum = (this._readByteOnly(curByte, size) >> offsetRight) & ((1 << (diff ? 8 - offsetRight : length)) - 1);

        if (diff && offsetLeft) {
            sum += (this._readByteOnly(lastByte++, size) & ((1 << offsetLeft) - 1)) << (diff-- << 3) - offsetRight;
        }

        while (diff) {
            sum += this._shl(this._readByteOnly(lastByte++, size), (diff-- << 3) - offsetRight);
        }

        return sum;
    },

    _readByteOnly:function (i, size) {
        return this._data[this._currentByte + size - i - 1];
    },

    _shl:function (a, b) {
        for (++b; --b; a = ((a %= 0x7fffffff + 1) & 0x40000000) === 0x40000000 ? a * 2 : (a - 0x40000000) * 2 + 0x7fffffff + 1);
        return a;
    },

    _checkSize:function (neededBits) {
        if (!(this._currentByte + Math.ceil(neededBits / 8) < this._data.length)) {
            throw new Error("Index out of bound");
        }
    },

    readCachedString:function () {
        return this._stringCache[this.readInt(false)];
    },

    isJSControlled:function () {
        return this._jsControlled;
    },

    getOwnerCallbackNames:function () {
        return this._ownerCallbackNames;
    },

    getOwnerCallbackNodes:function () {
        return this._ownerCallbackNodes;
    },

    getOwnerCallbackControlEvents:function(){
        return this._ownerCallbackEvents;
    },

    getOwnerOutletNames:function () {
        return this._ownerOutletNames;
    },

    getOwnerOutletNodes:function () {
        return this._ownerOutletNodes;
    },

    getNodesWithAnimationManagers:function () {
        return this._nodesWithAnimationManagers;
    },

    getAnimationManagersForNodes:function () {
        return this._animationManagerForNodes;
    },

    getAnimationManagers:function () {
        return this._animationManagers;
    },

    setAnimationManagers:function (animationManagers) {
        this._animationManagers = animationManagers;
    },

    addOwnerCallbackName:function (name) {
        this._ownerCallbackNames.push(name)
    },

    addOwnerCallbackNode:function (node) {
        this._ownerCallbackNodes.push(node);
    },

    addOwnerCallbackControlEvents:function(event){
        this._ownerCallbackEvents.push(event);
    },

    addDocumentCallbackName:function (name) {
        this._animationManager.addDocumentCallbackName(name);
    },

    addDocumentCallbackNode:function (node) {
        this._animationManager.addDocumentCallbackNode(node);
    },

    addDocumentCallbackControlEvents:function(controlEvents){
        this._animationManager.addDocumentCallbackControlEvents(controlEvents);
    },

    readFileWithCleanUp:function (cleanUp) {
        if (!this._readHeader())
            return null;
        if (!this._readStringCache())
            return null;
        if (!this._readSequences())
            return null;

        var node = this._readNodeGraph();
        this._animationManagers.setObject(this._animationManager, node);

        if (cleanUp)
            this._cleanUpNodeGraph(node);
        return node;
    },

    addOwnerOutletName: function(name){
         this._ownerOutletNames.push(name);
    },

    addOwnerOutletNode: function(node){
         if(node == null)
            return;

        this._ownerOutletNodes.push(node);
    },

    _cleanUpNodeGraph:function (node) {
        node.userObject = null;
        var getChildren = node.getChildren();
        for (var i = 0, len = getChildren.length; i < len; i++) {
            this._cleanUpNodeGraph(getChildren[i]);
        }
    },

    _readCallbackKeyframesForSeq:function(seq) {
        var numKeyframes = this.readInt(false);

        if (!numKeyframes)
            return true;

        var channel = new cc.BuilderSequenceProperty();
        var locJsControlled = this._jsControlled, locAnimationManager = this._animationManager, locKeyframes = channel.getKeyframes();
        for (var i = 0; i < numKeyframes; i++) {
            var time = this.readFloat();
            var callbackName = this.readCachedString();
            var callbackType = this.readInt(false);

            var value = [ callbackName, callbackType];

            var keyframe = new cc.BuilderKeyframe();
            keyframe.setTime(time);
            keyframe.setValue(value);

            if(locJsControlled)
                locAnimationManager.getKeyframeCallbacks().push(callbackType+":"+callbackName);

            locKeyframes.push(keyframe);
        }

        // Assign to sequence
        seq.setCallbackChannel(channel);

        return true;
    },

    _readSoundKeyframesForSeq:function(seq) {
        var numKeyframes = this.readInt(false);

        if (!numKeyframes)
            return true;

        var channel = new cc.BuilderSequenceProperty();
        var locKeyframes = channel.getKeyframes();
        for (var i = 0; i < numKeyframes; i++) {
            var time = this.readFloat();
            var soundFile = this.readCachedString();
            var pitch = this.readFloat();
            var pan = this.readFloat();
            var gain = this.readFloat();

            var value  = [soundFile, pitch, pan, gain];
            var keyframe = new cc.BuilderKeyframe();
            keyframe.setTime(time);
            keyframe.setValue(value);

            locKeyframes.push(keyframe);
        }

        // Assign to sequence
        seq.setSoundChannel(channel);
        return true;
    },
    _readSequences:function () {
        var sequences = this._animationManager.getSequences();
        var numSeqs = this.readInt(false);
        for (var i = 0; i < numSeqs; i++) {
            var seq = new cc.BuilderSequence();
            seq.setDuration(this.readFloat());
            seq.setName(this.readCachedString());
            seq.setSequenceId(this.readInt(false));
            seq.setChainedSequenceId(this.readInt(true));

            if (!this._readCallbackKeyframesForSeq(seq))
                return false;
            if (!this._readSoundKeyframesForSeq(seq))
                return false;

            sequences.push(seq);
        }
        this._animationManager.setAutoPlaySequenceId(this.readInt(true));
        return true;
    },

    readKeyframe:function (type) {
        var keyframe = new cc.BuilderKeyframe();
        keyframe.setTime(this.readFloat());
        var easingType = this.readInt(false);
        var easingOpt = 0;
        var value = null;

        if (easingType === CCB_KEYFRAME_EASING_CUBIC_IN
            || easingType === CCB_KEYFRAME_EASING_CUBIC_OUT
            || easingType === CCB_KEYFRAME_EASING_CUBIC_INOUT
            || easingType === CCB_KEYFRAME_EASING_ELASTIC_IN
            || easingType === CCB_KEYFRAME_EASING_ELASTIC_OUT
            || easingType === CCB_KEYFRAME_EASING_ELASTIC_INOUT) {
            easingOpt = this.readFloat();
        }

        keyframe.setEasingType(easingType);
        keyframe.setEasingOpt(easingOpt);

        if (type === CCB_PROPTYPE_CHECK) {
            value = this.readBool();
        } else if (type === CCB_PROPTYPE_FLOAT) {
            value = this.readFloat();
        } else if (type === CCB_PROPTYPE_BYTE) {
            value = this.readByte();
        } else if (type === CCB_PROPTYPE_INTEGER || type === CCB_PROPTYPE_INTEGERLABELED) {
            value = this.readInt(true);
        } else if (type === CCB_PROPTYPE_COLOR3) {
            var c;
            if (this.getFileVersion() >= 6) {
                c = this._readColor4V6();
                c = cc.color(c.r, c.g, c.b);
            } else {
                c = cc.color(this.readByte(), this.readByte(), this.readByte());
            }
            value = cc.Color3BWapper.create(c);
        } else if (type === CCB_PROPTYPE_COLOR4) {
            var c4 = this.getFileVersion() >= 6 ? this._readColor4V6() : {r:this.readByte(), g:this.readByte(), b:this.readByte(), a:this.readByte()};
            value = cc.Color3BWapper.create(cc.color(c4.r, c4.g, c4.b));
        } else if (type === CCB_PROPTYPE_FLOATXY) {
            value = [this.readFloat(), this.readFloat()];
        } else if (type === CCB_PROPTYPE_DEGREES) {
            value = this.readFloat();
        } else if (type === CCB_PROPTYPE_FLOATSCALE) {
            value = this.readFloat();
            this.readInt(false);
        } else if (type === CCB_PROPTYPE_SCALELOCK || type === CCB_PROPTYPE_POSITION || type === CCB_PROPTYPE_FLOATXY) {
            value = [this.readFloat(), this.readFloat()];
        } else if (type === CCB_PROPTYPE_SPRITEFRAME) {
            if (this.getFileVersion() >= 6) {
                value = this._readSpriteFrameV6();
            } else {
                var spriteSheet = this.readCachedString();
                var spriteFile = this.readCachedString();

                if (spriteSheet === "") {
                    spriteFile = this._ccbRootPath + spriteFile;
                    var texture = cc.textureCache.addImage(spriteFile);
                    var locContentSize = texture.getContentSize();
                    var bounds = cc.rect(0, 0, locContentSize.width, locContentSize.height);
                    value = new cc.SpriteFrame(texture, bounds);
                } else {
                    spriteSheet = this._ccbRootPath + spriteSheet;
                    var frameCache = cc.spriteFrameCache;
                    // Load the sprite sheet only if it is not loaded
                    if (this._loadedSpriteSheets.indexOf(spriteSheet) === -1) {
                        frameCache.addSpriteFrames(spriteSheet);
                        this._loadedSpriteSheets.push(spriteSheet);
                    }
                    value = frameCache.getSpriteFrame(spriteFile);
                }
            }
        } else if (type === CCB_PROPTYPE_STRING || type === CCB_PROPTYPE_TEXT) {
            value = this.readCachedString();
            if (this.getFileVersion() >= 6) {
                this.readBool();
            }
        }
        keyframe.setValue(value);
        return keyframe;
    },

    _readHeader:function () {
        /* If no bytes loaded, don't crash about it. */
        if (!this._data)
            return false;

        /* Read magic bytes */
        var magicBytes = this._readStringFromBytes(this._currentByte, 4, true);
        this._currentByte += 4;

        if (magicBytes !== 'ccbi') {
            return false;
        }

        /* Read version. */
        var version = this.readInt(false);
        if (version !== CCB_VERSION && version !== CCB_LEGACY_VERSION) {
            cc.log("WARNING! Incompatible ccbi file version (file: " + version + " reader: " + CCB_VERSION + ")");
            return false;
        }
        this._fileVersion = version;

        if (version >= 6) {
            // Newer ccbi files in this project omit the legacy jsControlled flag,
            // but still rely on document controllers/custom classes for outlets
            // and callbacks. Treat them as JS-controlled without consuming bits.
            this._jsControlled = true;
        } else {
            this._jsControlled = this.readBool();
        }
        this._animationManager._jsControlled = this._jsControlled;
        // no need to set if it is "jscontrolled". It is obvious.
        return true;
    },

    _readStringFromBytes:function (startIndex, strLen, reverse) {
        reverse = reverse || false;
        var strValue = "";
        var i, locData = this._data, locCurrentByte = this._currentByte;
        if (reverse) {
            for (i = strLen - 1; i >= 0; i--)
                strValue += String.fromCharCode(locData[locCurrentByte + i]);
        } else {
            for (i = 0; i < strLen; i++)
                strValue += String.fromCharCode(locData[locCurrentByte + i]);
        }
        return strValue;
    },

    _readStringCache:function () {
        var numStrings = this.readInt(false);
        for (var i = 0; i < numStrings; i++)
            this._readStringCacheEntry();
        return true;
    },

    _readStringCacheEntry:function () {
        var b0 = this.readByte();
        var b1 = this.readByte();

        var numBytes = b0 << 8 | b1;

        var str = "", locData = this._data, locCurrentByte = this._currentByte;
        for (var i = 0; i < numBytes; i++) {
            var hexChar = locData[locCurrentByte + i].toString("16").toUpperCase();
            hexChar = hexChar.length > 1 ? hexChar : "0" + hexChar;
            str += "%" + hexChar;
        }
        str = decodeURIComponent(str);

        this._currentByte += numBytes;
        this._stringCache.push(str);
    },

    _normalizeColorComponentV6:function (value) {
        return value <= 1 ? (0 | (value * 255)) : (0 | value);
    },

    _readColor4V6:function () {
        return {
            r:this._normalizeColorComponentV6(this.readFloat()),
            g:this._normalizeColorComponentV6(this.readFloat()),
            b:this._normalizeColorComponentV6(this.readFloat()),
            a:this._normalizeColorComponentV6(this.readFloat())
        };
    },

    _readSpriteFrameV6:function () {
        var spriteFile = this.readCachedString();
        this._lastSpriteFrameNameV6 = spriteFile || "";
        this._lastSpriteFrameWasEmptyV6 = !spriteFile;
        this._lastMissingSpriteFrameNameV6 = "";
        if (!spriteFile) {
            return null;
        }
        var frame = this._resolveSpriteFrameV6(spriteFile);
        if (!frame) {
            this._lastMissingSpriteFrameNameV6 = spriteFile;
            cc.log("SuperCat: missing CCB spriteFrame: " + spriteFile);
        }
        return frame;
    },

    _skipPhysicsBodyV6:function () {
        var bodyShape = this.readInt(false);
        this.readFloat(); // cornerRadius

        if (bodyShape === 1) {
            this.readFloat();
            this.readFloat();
        } else {
            var polygonCount = this.readInt(false);
            for (var i = 0; i < polygonCount; i++) {
                var pointCount = this.readInt(false);
                for (var j = 0; j < pointCount; j++) {
                    this.readFloat();
                    this.readFloat();
                }
            }
        }

        this.readBool(); // dynamic
        this.readBool(); // affectedByGravity
        this.readBool(); // allowsRotation

        this.readFloat(); // density
        this.readFloat(); // friction
        this.readFloat(); // elasticity

        if (this.readBool()) {
            this.readFloat();
        }
        if (this.readBool()) {
            this.readFloat();
        }

        this.readInt(true); // categoryBitmask
        this.readInt(true); // contactTestBitmask
        this.readInt(true); // collisionBitmask

        this.readFloat(); // velocityX
        this.readFloat(); // velocityY
        this.readFloat(); // velocityLimit
        this.readFloat(); // angleVelocity
        this.readFloat(); // angleVelocityLimit
        this.readFloat(); // linearDamping
        this.readFloat(); // angularDamping
    },

    _readNodeGraph:function (parent) {
        /* Read class name. */
        var className = this.readCachedString();

        var jsControlledName = null;
        var customClassName = null;
        var locJsControlled = this._jsControlled, locActionManager = this._animationManager;
        if (this.getFileVersion() >= 6) {
            customClassName = this.readCachedString();
            if (customClassName && customClassName.length > 0) {
                jsControlledName = customClassName;
            }
        } else if (locJsControlled) {
            jsControlledName = this.readCachedString();
        }

        var memberVarAssignmentType = this.readInt(false);
        var memberVarAssignmentName;
        if (memberVarAssignmentType !== CCB_TARGETTYPE_NONE) {
            memberVarAssignmentName = this.readCachedString();
        }

        var ccNodeLoader = this._ccNodeLoaderLibrary.getCCNodeLoader(className);
        if (!ccNodeLoader && this.getFileVersion() >= 6) {
            if (className === "CCButton") {
                ccNodeLoader = this._ccNodeLoaderLibrary.getCCNodeLoader("CCControlButton");
            }
        }
        if (!ccNodeLoader) {
            ccNodeLoader = this._ccNodeLoaderLibrary.getCCNodeLoader("CCNode");
            //cc.log("no corresponding node loader for" + className);
            //return null;
        }
        var node = ccNodeLoader.loadCCNode(parent, this);

        //set root node
        if (!locActionManager.getRootNode())
            locActionManager.setRootNode(node);

        if ((locJsControlled || this.getFileVersion() >= 6) && jsControlledName && node === locActionManager.getRootNode()) {
            locActionManager.setDocumentControllerName(jsControlledName);
        }

        //read animated properties
        var seqs = new cc._Dictionary();
        this._animatedProps = [];

        var i, locAnimatedProps = this._animatedProps;
        var numSequence = this.readInt(false);
        for (i = 0; i < numSequence; ++i) {
            var seqId = this.readInt(false);
            var seqNodeProps = new cc._Dictionary();

            var numProps = this.readInt(false);

            for (var j = 0; j < numProps; ++j) {
                var seqProp = new cc.BuilderSequenceProperty();
                seqProp.setName(this.readCachedString());
                seqProp.setType(this.readInt(false));

                locAnimatedProps.push(seqProp.getName());
                var numKeyframes = this.readInt(false);
                var locKeyframes = seqProp.getKeyframes();
                for (var k = 0; k < numKeyframes; ++k) {
                    var keyFrame = this.readKeyframe(seqProp.getType());
                    locKeyframes.push(keyFrame);
                }
                seqNodeProps.setObject(seqProp, seqProp.getName());
            }
            seqs.setObject(seqNodeProps, seqId);
        }

        if (seqs.count() > 0)
            locActionManager.addNode(node, seqs);

        //read properties
        ccNodeLoader.parseProperties(node, parent, this);

        if (this.getFileVersion() >= 6) {
            var hasPhysicsBody = this.readBool();
            if (hasPhysicsBody) {
                this._skipPhysicsBodyV6();
            }
        }

        //handle sub ccb files(remove middle node)
        var isCCBFileNode = node instanceof cc.BuilderFile;
        if (isCCBFileNode) {
            var embeddedNode = node.getCCBFileNode();
            embeddedNode.setPosition(node.getPosition());
            embeddedNode.setRotation(node.getRotation());
            embeddedNode.setScaleX(node.getScaleX());
            embeddedNode.setScaleY(node.getScaleY());
            embeddedNode.setTag(node.getTag());
            embeddedNode.setVisible(true);
            //embeddedNode.ignoreAnchorPointForPosition(node.isIgnoreAnchorPointForPosition());

            locActionManager.moveAnimationsFromNode(node, embeddedNode);
            node.setCCBFileNode(null);
            node = embeddedNode;
        }
        var target = null, locMemberAssigner = null;
        if (memberVarAssignmentType !== CCB_TARGETTYPE_NONE) {
            if (!locJsControlled) {
                if (memberVarAssignmentType === CCB_TARGETTYPE_DOCUMENTROOT) {
                    target = locActionManager.getRootNode();
                } else if (memberVarAssignmentType === CCB_TARGETTYPE_OWNER) {
                    target = this._owner;
                }

                if (target) {
                    var assigned = false;

                    if (target.onAssignCCBMemberVariable)
                        assigned = target.onAssignCCBMemberVariable(target, memberVarAssignmentName, node);

                    locMemberAssigner = this._ccbMemberVariableAssigner;
                    if (!assigned && locMemberAssigner != null && locMemberAssigner.onAssignCCBMemberVariable) {
                        locMemberAssigner.onAssignCCBMemberVariable(target, memberVarAssignmentName, node);
                    }
                }
            } else {
                if (memberVarAssignmentType === CCB_TARGETTYPE_DOCUMENTROOT) {
                    locActionManager.addDocumentOutletName(memberVarAssignmentName);
                    locActionManager.addDocumentOutletNode(node);
                } else {
                    this._ownerOutletNames.push(memberVarAssignmentName);
                    this._ownerOutletNodes.push(node);
                }
            }
        }

        // Assign custom properties.
        if (ccNodeLoader.getCustomProperties().length > 0) {
            var customAssigned = false;
            if(!locJsControlled) {
                target = node;
                if(target != null && target.onAssignCCBCustomProperty != null) {
                    var customProperties = ccNodeLoader.getCustomProperties();
                    var customPropKeys = customProperties.allKeys();
                    for(i = 0;i < customPropKeys.length;i++){
                        var customPropValue = customProperties.objectForKey(customPropKeys[i]);
                        customAssigned = target.onAssignCCBCustomProperty(target, customPropKeys[i], customPropValue);
                        locMemberAssigner = this._ccbMemberVariableAssigner;
                        if(!customAssigned && (locMemberAssigner != null) && (locMemberAssigner.onAssignCCBCustomProperty != null))
                            customAssigned = locMemberAssigner.onAssignCCBCustomProperty(target, customPropKeys[i], customPropValue);
                    }
                }
            }
        }

        this._animatedProps = null;

        /* Read and add children. */
        var numChildren = this.readInt(false);
        for (i = 0; i < numChildren; i++) {
            var child = this._readNodeGraph(node);
            node.addChild(child);
        }

        // FIX ISSUE #1860: "onNodeLoaded will be called twice if ccb was added as a CCBFile".
        // If it's a sub-ccb node, skip notification to CCNodeLoaderListener since it will be
        // notified at LINE #734: CCNode * child = this->readNodeGraph(node);
        if (!isCCBFileNode) {
            // Call onNodeLoaded
            if (node != null && node.onNodeLoaded)
                node.onNodeLoaded(node, ccNodeLoader);
            else if (this._ccNodeLoaderListener != null)
                this._ccNodeLoaderListener.onNodeLoaded(node, ccNodeLoader);
        }

        return node;
    },

    _getBit:function () {
        var bit = (this._data[this._currentByte] & (1 << this._currentBit)) !== 0;
        this._currentBit++;

        if (this._currentBit >= 8) {
            this._currentBit = 0;
            this._currentByte++;
            if(this._currentByte > this._data.length)
                throw new Error("out of the data bound");
        }
        return bit;
    },

    _alignBits:function () {
        if (this._currentBit) {
            this._currentBit = 0;
            this._currentByte++;
        }
    },

    _readUTF8:function () {
    }
});

cc.BuilderReader._ccbResolutionScale = 1;
cc.BuilderReader.setResolutionScale = function(scale){
    cc.BuilderReader._ccbResolutionScale = scale;
};

cc.BuilderReader.getResolutionScale = function () {
    return cc.BuilderReader._ccbResolutionScale;
};

cc.BuilderReader.loadAsScene = function (ccbFilePath, owner, parentSize, ccbRootPath) {
    ccbRootPath = ccbRootPath || cc.BuilderReader.getResourcePath();

    var getNode = cc.BuilderReader.load(ccbFilePath, owner, parentSize, ccbRootPath);

    var scene = new cc.Scene();
    scene.addChild(getNode);
    return scene;
};

cc.BuilderReader._controllerClassCache = {};
cc.BuilderReader.registerController = function(controllerName, controller){
    cc.BuilderReader._controllerClassCache[controllerName] = (typeof controller === "function") ? controller : cc.Class.extend(controller);
};
cc.BuilderReader._resolveControllerClass = function (controllerName) {
    var controllerClassCache = cc.BuilderReader._controllerClassCache;
    var controllerClass = controllerClassCache[controllerName];
    if (!controllerClass) {
        var controllerGlobalRoot = (typeof window !== "undefined") ? window : ((typeof globalThis !== "undefined") ? globalThis : this);
        var controllerDef = controllerGlobalRoot ? controllerGlobalRoot[controllerName] : null;
        if (!controllerDef && controllerGlobalRoot && controllerName && controllerName.length > 0) {
            var normalizedControllerName = controllerName.charAt(0).toUpperCase() + controllerName.slice(1);
            controllerDef = controllerGlobalRoot[normalizedControllerName];
        }
        if (controllerDef) {
            controllerClass = (typeof controllerDef === "function") ? controllerDef : cc.Class.extend(controllerDef);
            controllerClassCache[controllerName] = controllerClass;
            cc.log("Auto-registered controller: " + controllerName);
        } else if (typeof vee !== "undefined" && vee.Class && vee.Class.extend) {
            controllerClass = vee.Class.extend({});
            controllerClassCache[controllerName] = controllerClass;
            cc.log("Controller fallback stub: " + controllerName);
        }
    }
    return controllerClass;
};
cc.BuilderReader._attachDocumentController = function (innerNode, animationManager, owner) {
    if (!innerNode || !animationManager) {
        return null;
    }

    innerNode.animationManager = animationManager;

    var controllerName = animationManager.getDocumentControllerName();
    if (!controllerName) {
        return null;
    }
    if (innerNode.controller && innerNode.controller.controllerName === controllerName) {
        return innerNode.controller;
    }

    var controllerClass = cc.BuilderReader._resolveControllerClass(controllerName);
    if (!controllerClass) {
        throw new Error("Can not find controller : " + controllerName);
    }

    var controller = new controllerClass();
    controller.controllerName = controllerName;
    innerNode.controller = controller;
    controller.rootNode = innerNode;
    if (typeof __supercatBootTrace === "function") {
        __supercatBootTrace("attach controller " + controllerName);
    }
    if ((controllerName === "LyGame" || controllerName === "lygame") && typeof game !== "undefined" && game.Data) {
        game.Data.oLyGame = controller;
        if (typeof __supercatBootTrace === "function") {
            __supercatBootTrace("game.Data.oLyGame assigned during attach");
        }
    }

    var callbackName, callbackNode, callbackControlEvents, outletName, outletNode;
    var j;

    var documentCallbackNames = animationManager.getDocumentCallbackNames();
    var documentCallbackNodes = animationManager.getDocumentCallbackNodes();
    var documentCallbackControlEvents = animationManager.getDocumentCallbackControlEvents();
    for (j = 0; j < documentCallbackNames.length; j++) {
        callbackName = documentCallbackNames[j];
        callbackNode = documentCallbackNodes[j];
        callbackControlEvents = documentCallbackControlEvents[j];
        if(callbackNode instanceof cc.ControlButton)
            callbackNode.addTargetWithActionForControlEvents(controller, controller[callbackName], callbackControlEvents);
        else
            callbackNode.setCallback(controller[callbackName], controller);
    }

    var documentOutletNames = animationManager.getDocumentOutletNames();
    var documentOutletNodes = animationManager.getDocumentOutletNodes();
    for (j = 0; j < documentOutletNames.length; j++) {
        outletName = documentOutletNames[j];
        outletNode = documentOutletNodes[j];
        controller[outletName] = outletNode;
    }

    if (controller.onDidLoadFromCCB && cc.isFunction(controller.onDidLoadFromCCB))
        controller.onDidLoadFromCCB();

    var keyframeCallbacks = animationManager.getKeyframeCallbacks();
    for (j = 0; j < keyframeCallbacks.length; j++) {
        var callbackSplit = keyframeCallbacks[j].split(":");
        var callbackType = callbackSplit[0];
        var kfCallbackName = callbackSplit[1];

        if (callbackType == 1){
            animationManager.setCallFunc(cc.callFunc(controller[kfCallbackName], controller), keyframeCallbacks[j]);
        } else if (callbackType == 2 && owner) {
            animationManager.setCallFunc(cc.callFunc(owner[kfCallbackName], owner), keyframeCallbacks[j]);
        }
    }

    return controller;
};
cc.BuilderReader.load = function (ccbFilePath, owner, parentSize, ccbRootPath) {
    ccbRootPath = ccbRootPath || cc.BuilderReader.getResourcePath();
    var reader = new cc.BuilderReader(cc.NodeLoaderLibrary.newDefaultCCNodeLoaderLibrary());
    reader.setCCBRootPath(ccbRootPath);
    if((ccbFilePath.length < 5)||(ccbFilePath.toLowerCase().lastIndexOf(".ccbi") !== ccbFilePath.length - 5))
        ccbFilePath = ccbFilePath + ".ccbi";

    var node = reader.readNodeGraphFromFile(ccbFilePath, owner, parentSize);
    var i;
    var callbackName, callbackNode, callbackControlEvents, outletName, outletNode;
    // Assign owner callbacks & member variables
    if (owner) {
        // Callbacks
        var ownerCallbackNames = reader.getOwnerCallbackNames();
        var ownerCallbackNodes = reader.getOwnerCallbackNodes();
        var ownerCallbackControlEvents = reader.getOwnerCallbackControlEvents();
        for (i = 0; i < ownerCallbackNames.length; i++) {
            callbackName = ownerCallbackNames[i];
            callbackNode = ownerCallbackNodes[i];
            callbackControlEvents = ownerCallbackControlEvents[i];
            if(callbackNode instanceof cc.ControlButton)
                callbackNode.addTargetWithActionForControlEvents(owner, owner[callbackName], callbackControlEvents);        //register all type of events
            else
                callbackNode.setCallback(owner[callbackName], owner);
        }

        // Variables
        var ownerOutletNames = reader.getOwnerOutletNames();
        var ownerOutletNodes = reader.getOwnerOutletNodes();
        for (i = 0; i < ownerOutletNames.length; i++) {
            outletName = ownerOutletNames[i];
            outletNode = ownerOutletNodes[i];
            owner[outletName] = outletNode;
        }
    }

    var nodesWithAnimationManagers = reader.getNodesWithAnimationManagers();
    var animationManagersForNodes = reader.getAnimationManagersForNodes();
    if(!nodesWithAnimationManagers || !animationManagersForNodes)
        return node;

    // Attach animation managers to nodes and assign root node callbacks and member variables
    for (i = 0; i < nodesWithAnimationManagers.length; i++) {
        var innerNode = nodesWithAnimationManagers[i];
        var animationManager = animationManagersForNodes[i];
        cc.BuilderReader._attachDocumentController(innerNode, animationManager, owner);
    }

    // Auto play animations only when the CCB actually declares an autoplay sequence.
    var autoPlaySequenceId = animationManager.getAutoPlaySequenceId();
    if (autoPlaySequenceId !== -1) {
        animationManager.runAnimations(autoPlaySequenceId, 0);
    }

    return node;
};

cc.BuilderReader._resourcePath = "";
cc.BuilderReader.setResourcePath = function (rootPath) {
    cc.BuilderReader._resourcePath = rootPath;
};

cc.BuilderReader.getResourcePath = function () {
    return cc.BuilderReader._resourcePath;
};

cc.BuilderReader.lastPathComponent = function (pathStr) {
    var slashPos = Math.max(pathStr.lastIndexOf("/"), pathStr.lastIndexOf("\\"));
    if (slashPos !== -1) {
        return pathStr.substring(slashPos + 1);
    }
    return pathStr;
};

cc.BuilderReader.deletePathExtension = function (pathStr) {
    var dotPos = pathStr.lastIndexOf(".");
    if (dotPos !== -1) {
        return pathStr.substring(0, dotPos);
    }
    return pathStr;
};

cc.BuilderReader.toLowerCase = function (sourceStr) {
    return sourceStr.toLowerCase();
};

cc.BuilderReader.endsWith = function (sourceStr, ending) {
    if (sourceStr.length >= ending.length)
        return (sourceStr.lastIndexOf(ending) === 0);
    else
        return false;
};

cc.BuilderReader.concat = function (stringA, stringB) {
    return stringA + stringB;
};

cc.loader.register(["ccbi"], cc._binaryLoader);
